header:
  title: "Nojiko Dashboard"
  showLogo: true
  showWeather: true
  latitude: 43.65
  longitude: -79.38

statusCards:
  - title: "GitHub Repositories"
    icon: "github"
    showMockData: true
    repositories:
      - owner: "tanq16"
        repo: "nojiko"
      - owner: "torvalds"
        repo: "linux"

thumbFeeds:
  - title: "Latest YouTube Videos"
    icon: "youtube"
    feedType: "youtube"
    showMockData: true
    channels:
      - "UC..."
      - "UC..."

bookmarks:
  - category: "Social Media"
    color: "ctp-green"
    links:
      - name: "Twitter / X"
        url: "#"
        icon: "twitter"
      - name: "YouTube"
        url: "#"
  - category: "Development"
    color: "ctp-yellow"
    folders:
      - name: "Frameworks"
        links:
          - name: "React Docs"
            url: "#"
            icon: "dot"
