ghToken: "" # Add your GitHub token here if you have one

header:
  title: "Nojiko Dashboard"
  showLogo: false
  showWeather: true
  latitude: 43.65
  longitude: -79.38

statusCards:
  - title: "Project Status"
    icon: "github"
    type: "github"
    cards:
      - owner: "tanq16"
        repo: "nojiko"
      - owner: "torvalds"
        repo: "linux"
  - title: "Service Status"
    icon: "bar-chart-3"
    type: "service"
    cards:
      - name: "API Server"
      - name: "Database"

thumbFeeds:
  - title: "Latest YouTube Videos"
    icon: "youtube"
    feedType: "youtube"
    channels:
      - "MrBeast"
      - "LinusTechTips"

bookmarks:
  - category: "Social Media"
    color: "ctp-green"
    links:
      - name: "Twitter / X"
        url: "#"
        icon: "twitter"
      - name: "YouTube"
        url: "#"
  - category: "Development"
    color: "ctp-yellow"
    folders:
      - name: "Frameworks"
        links:
          - name: "React Docs"
            url: "#"
            icon: "dot"
